GET http://localhost:5000/history?6388f8521968f42442b595fe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXJ0Ijp7Iml0ZW1zIjpbeyJwcm9kdWN0SWQiOiI2MzdjNWEzNDU1NmEwNjQ3MDEzNDIzZDYiLCJxdWFudGl0eSI6MSwiX2lkIjoiNjM3ZDlmMjAwZGU5ZTg2YjJlYzg4NjQ1In1dfSwiX2lkIjoiNjM3YzZmMzgyZDcxNjkxYjkwZmQzMDNlIiwibmFtZSI6InNhbmciLCJwYXNzd29yZCI6IiQyYSQxMiQuMUkxWlpHcW1LMTNlVjVETEsuSVJPcXBabFNVd2xhNTJZUkhLWkg3MlEuTjJpOEdMbEZIaSIsImVtYWlsIjoic2FuZ0B0ZXN0LmNvbSIsIl9fdiI6MCwiaWF0IjoxNjY5MzYxOTUwfQ.MCOWRkuPMJ0x4E_Xe9zim_-kW32VRCp3l07H9-Hr6Dc
